### PR TITLE
How to guides to configure Loki daemon as a systemd service

### PR DESCRIPTION
**Pull request by IldeGaldur**
Guides to configure loki daemon as a service

### CODE REVIEW

**Comment by KeeJef** [comment]
Have tried to condense this down into a single guide, which can be followed simply. My version is lacking the detail on testnet specific parts but i think most people are interested in doing this for mainnet.

**Comment by IldeGaldur** [comment]
> Have tried to condense this down into a single guide, which can be followed simply. My version is lacking the detail on testnet specific parts but i think most people are interested in doing this for mainnet.

Great idea! I was also thinking it was overcomplicated for a simple guide like this.
I removed the option of downloading the config file in order to simplify it even further. No need to change the config file in the future if it needs to be modified. Updates can be commited to the guide only.
I introduced a couple of comments on the text for people who want to run the service for Testnet.
I also wrote a couple of lines for people who are running the service node as root as their home path does not start at  /home.

**Comment by KeeJef** [comment]
Okay I've had a final look over this and Squashed your commits and added a few of mine, i will get one more person to review this before merging

**Comment by IldeGaldur** [comment]
I think changes on WorkingDirectory were not necessary as If set to "~", the home directory of the user specified in User= is used.
Also, this change implies more changes on next step (number 5). 
In order to keep it simple I would revert back this change.

**Comment by KeeJef** [comment]
@IldeGaldur okay feel free to add back the ~, but maybe put an explanation in section 5 to explain this

**Comment by IldeGaldur** [comment]
OK, I'll do it. 
This made me think that, to simplify it even further, I can change homes path to  ~ on commands. For example: /home/YOUR_USERNAME/YOUR_LOKI_FILES_FOLDER/./lokid print_sn_status 
and
/root/YOUR_LOKI_FILES_FOLDER/./lokid print_sn_status
will be switched to 
~/YOUR_LOKI_FILES_FOLDER/./lokid print_sn_status

If you're OK with that, I'll change it as well.

**Comment by KeeJef** [comment]
Yeah go ahead

**Comment by IldeGaldur** [comment]
Changes made!

**Pull request merged**
